### ISSUE TITLE
mongodb 3 (3.2) support?

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#225]
have you guys tried the newer versions? 

any special instructions on setup (other than export via mongo dump then binary install of newer and reimport https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ )

Ubuntu LTS use mongo 2.0.4 -> 2.6

Newest build is 3.2 (allegedly) stable. Comes with new compression on disk engine and better parallel task / insert search etc support (apparently orders of magnitude better according to devs for some use cases )

https://docs.mongodb.com/manual/tutorial/backup-and-restore-tools/ 
https://www.mongodb.com/blog/post/whats-new-mongodb-30-part-3-performance-efficiency-gains-new-storage-architecture

https://docs.mongodb.com/manual/core/wiredtiger/

https://docs.mongodb.com/manual/release-notes/3.2-upgrade/

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by KillerInstinct** [comment]
I use MongoDB 3.0 with WiredTiger with no problems. Just make sure you using pymongo version 3.0 or higher.

WiredTiger is the version you want to use if you want compression, be warned though that the config syntax between mongo 2.x and 3.x is completely different.

**Comment by mallorybobalice** [comment]
Hello KI. Thank you for the response. 
Yep you're right pymongo too 
Would you mind and perhaps posting an example config /if any code changes are required

**Comment by KillerInstinct** [comment]
Sure -- no code changes required on the cuckoo side. Below is a config, you'll want to modify the cache size, compression and network related stuff per your environment. I don't compress because it's fastest. With the type of data Cuckoo generates (quite large dictionaries of data in some cases) there is a performance hit when searching for tasks. Loading them is a bit faster though in my testing (with no compression, didn't test with fast compression) 
```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 16
      journalCompressor: none

#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


#processManagement:

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```
